spring.datasource.url=jdbc:postgresql://localhost:5432/otp_db
spring.datasource.username=postgres
spring.datasource.password=123

jwt.secret=supersecretkeysupersecretkey123456
jwt.expiration=900000