email.username=lucykorotkovas@yandex.ru
email.password=ydxpggpwkxrzrkxq
email.from=lucykorotkovas@yandex.ru

mail.smtp.host=smtp.yandex.ru
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.starttls.required=true
mail.smtp.ssl.protocols=TLSv1.2